# Generated by Django 3.2.15 on 2023-05-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('price', models.FloatField(blank=True, null=True)),
                ('photo', models.BinaryField(default=b'')),
                ('status', models.CharField(choices=[('Available', 'Disponible'), ('Current Unavailable', 'No Disponible')], default='Available', max_length=20)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
