# Generated by Django 3.2.15 on 2023-05-24 14:18

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_items_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='photo',
            field=models.ImageField(upload_to=items.models.content_file_name),
        ),
    ]
